### ISSUE TITLE
Menu and page empty after login

### ISSUE THREAD

**Issue by net4u** [berkansasmaz/ketum#67]
Hi,

First of all I have to say that I am not familiar with WebPack and I did not found a way to install it on Visual Studio 2019 on Windows. So I made a change in Startup.cs to bypass it.
`public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                
                //app.UseDeveloperExceptionPage();

                // Webpack initialization with hot-reload.
                //app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                //{
                //    HotModuleReplacement = true
                //});
                
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }
            else
            {`
Also I made little changes for using MSSQL instead of Postgress.
So, after login I have this
![image](https://user-images.githubusercontent.com/255743/86230814-48dca980-bb9a-11ea-8477-69e692f4043f.png)
and respectively
![image](https://user-images.githubusercontent.com/255743/86230950-77f31b00-bb9a-11ea-88e2-20b3dcd77c4e.png)

I suppose that is caused by bundling, but I don't know how to bypass this.

Off-topic: something is wrong with github home page of project since if by hazard is browsed with (old) Edge browser, all computer is nearly freezing. It's so severe that I am not able to inspect page.

**Comment by berkansasmaz** [comment]
Hello @net4u

I'm very sorry that I replied late, but I have good news!

The 1.0.0 version of Ketum will be released shortly. In this version, the back-end and front-end have been completely rewritten. It was fine although there were some bugs in the previous version, but it lacked maintainable and extensible code. For this reason, we will now be able to respond to requests in a much shorter time. Also, the power of WebAssembly is now with us.

I hope you enjoy the app when the 1.0.0 version is released. We look forward to your feedback.
